spring:
  application:
    name: wg_invite_gateway
  profiles:
    active: dev

server:
  port: 2020
  servlet:
    context-path: /
#  contextPath: /
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:5050/authserver/oauth/token
      userAuthorizationUri: http://localhost:5050/authserver/oauth/authorize
      clientId: InviteEntry
      clientSecret: invitepass
     # pre-established-redirect-uri: http://localhost:2020/invite
#      use-current-uri: false
    resource:
#      token-info-uri: http://localhost:5050/authserver/user/me
      prefer-token-info: false
      userInfoUri: http://localhost:5050/authserver/user/me
#      jwt:
#        key-value: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/Q7+zlmCj8e1+duAEfJ
#          o6vuojdFHHZqZ70YzsKQ2+09oceH9cs3cLjsX8mYkZJX0qjlHOhtppBsjQtH0uhy
#          sVImLsk5lB/EfuB3FFkBp1/Bz5AdpcnVtLfCtjvjkAd0RCxr95y9eQw1Qx/npwQ6
#          JuPxOohEpI5PSijcC+JuvHWv5Af/BcrKUAa/gTUwilW2wHrJh+kJpvTNQGEFsFFN
#          OWTMT5JfqMO5q+bOS6zqLYyvpFJVaj4WD2f+Zxi9BlF7RO5WFg9cI08Jki1U6pMj
#          OXnHTP5kUnI/yXr62Gsz5txfAnNzNwoktv21v2wch7tV4d3L5NZRLUyeo/NCeWDa
#          jwIDAQAB
#          -----END PUBLIC KEY-----
    sso:
      login-path: /

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2

# Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:8081/*
# and automatically includes our OAuth2 token in the request headers
zuul:
  routes:
    wg_invite_entry:
      path: /api/**
      url: http://localhost:6000
    user:
      path: /user/**
      url: http://localhost:6000/user
  add-proxy-headers: true
  sensitive-headers:
  debug:
    request: true


logging:
  level:
    spring:
      web:
        client:
          MessageTracing:
            sent: debug
            received: debug
    org:
      springframework:
        cloud:
          netflix: trace
        security: debug

debug: true
trace: true
